services:
  - type: web
    name: punto-whats
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DEEPSEEK_API_KEY
        fromEnv: true