name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # Cada 5 min

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping punto-whats
        run: curl -s https://ia-xel.onrender.com > /dev/null
